# Generated by Django 5.1.6 on 2025-06-12 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                ("state_code", models.IntegerField(primary_key=True, serialize=False)),
                ("state_name", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "district_code",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("district_name", models.CharField(max_length=40)),
                (
                    "state_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gwa.state"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subdistrict",
            fields=[
                (
                    "subdistrict_code",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("subdistrict_name", models.CharField(max_length=40)),
                (
                    "district_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gwa.district"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "village_code",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("village_name", models.CharField(max_length=100)),
                ("population_2011", models.IntegerField()),
                (
                    "subdistrict_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gwa.subdistrict",
                    ),
                ),
            ],
        ),
    ]
