# Generated by Django 5.1.6 on 2025-06-12 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwa", "0002_well"),
    ]

    operations = [
        migrations.AlterField(
            model_name="well",
            name="village_code",
            field=models.ForeignKey(
                db_column="village_code",
                on_delete=django.db.models.deletion.CASCADE,
                to="gwa.village",
            ),
        ),
    ]
