# Generated by Django 5.1.6 on 2025-05-27 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stp_suitability", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StpFile",
        ),
    ]
