"""done

Revision ID: 9d327adc1a23
Revises: 
Create Date: 2025-06-04 10:58:12.598513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d327adc1a23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stp_priority_raster',
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stp_priority_raster_id'), 'stp_priority_raster', ['id'], unique=True)
    op.create_table('stp_priority_visual_raster',
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('sld_path', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stp_priority_visual_raster_id'), 'stp_priority_visual_raster', ['id'], unique=True)
    op.create_table('stp_river',
    sa.Column('River_Code', sa.Integer(), nullable=False),
    sa.Column('River_Name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('River_Code', 'id'),
    sa.UniqueConstraint('River_Code')
    )
    op.create_index(op.f('ix_stp_river_id'), 'stp_river', ['id'], unique=True)
    op.create_table('stp_state',
    sa.Column('state_code', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('state_code', 'id'),
    sa.UniqueConstraint('state_code')
    )
    op.create_index(op.f('ix_stp_state_id'), 'stp_state', ['id'], unique=True)
    op.create_table('stp_sutability_raster',
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('raster_category', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stp_sutability_raster_id'), 'stp_sutability_raster', ['id'], unique=True)
    op.create_table('stp_sutability_visual_raster',
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('sld_path', sa.String(), nullable=False),
    sa.Column('raster_category', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stp_sutability_visual_raster_id'), 'stp_sutability_visual_raster', ['id'], unique=True)
    op.create_table('stp_district',
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(), nullable=False),
    sa.Column('state_code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['state_code'], ['stp_state.state_code'], ),
    sa.PrimaryKeyConstraint('district_code', 'id'),
    sa.UniqueConstraint('district_code')
    )
    op.create_index(op.f('ix_stp_district_id'), 'stp_district', ['id'], unique=True)
    op.create_table('stp_stretches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Stretch_ID', sa.Integer(), nullable=False),
    sa.Column('river_Code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['river_Code'], ['stp_river.River_Code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stp_drain',
    sa.Column('Drain_No', sa.Integer(), nullable=False),
    sa.Column('stretch_id', sa.Integer(), nullable=False),
    sa.Column('River_code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stretch_id'], ['stp_stretches.id'], ),
    sa.PrimaryKeyConstraint('Drain_No', 'id'),
    sa.UniqueConstraint('Drain_No')
    )
    op.create_index(op.f('ix_stp_drain_id'), 'stp_drain', ['id'], unique=True)
    op.create_table('stp_subdistrict',
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.Column('subdistrict_name', sa.String(), nullable=False),
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_code'], ['stp_district.district_code'], ),
    sa.PrimaryKeyConstraint('subdistrict_code', 'id'),
    sa.UniqueConstraint('subdistrict_code')
    )
    op.create_index(op.f('ix_stp_subdistrict_id'), 'stp_subdistrict', ['id'], unique=True)
    op.create_table('stp_catchment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('GRIDCODE', sa.Integer(), nullable=False),
    sa.Column('Drain_No', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['Drain_No'], ['stp_drain.Drain_No'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('stp_towns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('classs', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=False),
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subdistrict_code'], ['stp_subdistrict.subdistrict_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stp_towns')
    op.drop_table('stp_catchment')
    op.drop_index(op.f('ix_stp_subdistrict_id'), table_name='stp_subdistrict')
    op.drop_table('stp_subdistrict')
    op.drop_index(op.f('ix_stp_drain_id'), table_name='stp_drain')
    op.drop_table('stp_drain')
    op.drop_table('stp_stretches')
    op.drop_index(op.f('ix_stp_district_id'), table_name='stp_district')
    op.drop_table('stp_district')
    op.drop_index(op.f('ix_stp_sutability_visual_raster_id'), table_name='stp_sutability_visual_raster')
    op.drop_table('stp_sutability_visual_raster')
    op.drop_index(op.f('ix_stp_sutability_raster_id'), table_name='stp_sutability_raster')
    op.drop_table('stp_sutability_raster')
    op.drop_index(op.f('ix_stp_state_id'), table_name='stp_state')
    op.drop_table('stp_state')
    op.drop_index(op.f('ix_stp_river_id'), table_name='stp_river')
    op.drop_table('stp_river')
    op.drop_index(op.f('ix_stp_priority_visual_raster_id'), table_name='stp_priority_visual_raster')
    op.drop_table('stp_priority_visual_raster')
    op.drop_index(op.f('ix_stp_priority_raster_id'), table_name='stp_priority_raster')
    op.drop_table('stp_priority_raster')
    # ### end Alembic commands ###
